export let Attractions = [
    { value: 'trollstigen' },
    { value: 'geiranger' },
    { value: 'norway' },
    { value: 'lofoten' },
    { value: 'northern lights' },
    { value: 'laks' },
    { value: 'rjukan' },
    { value: 'polar bear' },
    { value: 'besseggen' },
    { value: 'nor' },
    { value: 'nord' },
    { value: 'north' },
    { value: 'ski' },
    { value: 'viking' },
    { value: 'aurora borealis' },
    { value: 'ice' },
    { value: 'reindeer' },
    { value: 'elk' },
    { value: 'glacier' },
    { value: 'arctic cathedral' },
    { value: 'fjord' },
    { value: 'hardangervidda' },
    { value: 'hardanger' },
    { value: 'oslo' },
    { value: 'bergen' },
    { value: 'trondheim' },
    { value: 'tromso' },
    { value: 'jotunheimen' },
    { value: 'cross country skiing' }
  ]